services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - ollama
    volumes:
      - ./keyframes:/keyframes
      - ./db:/db

  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
